CREATE TABLE Orders (
  ID SERIAL PRIMARY KEY,
  Open BOOLEAN
);

CREATE TABLE Item (
  ID SERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Description TEXT NOT NULL,
  Price NUMERIC NOT NULL
);

CREATE TABLE OrderItem (
  Order_ID INTEGER REFERENCES Orders(ID),
  Item_ID INTEGER REFERENCES Item(ID)
);

CREATE TABLE Users (
  ID SERIAL PRIMARY KEY,
  Username TEXT NOT NULL,
  PasswordHash TEXT NOT NULL,
  Role TEXT,
  Cart_ID INTEGER REFERENCES Orders(ID)
);