CREATE TABLE Users (
  ID SERIAL PRIMARY KEY,
  Username TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  Role TEXT
);

CREATE TABLE Orders (
  ID SERIAL PRIMARY KEY,
  Open BOOLEAN,
  User_ID INTEGER REFERENCES Users(ID)
);

CREATE TABLE Item (
  ID SERIAL PRIMARY KEY,
  Name TEXT NOT NULL,
  Description TEXT NOT NULL,
  Price NUMERIC NOT NULL
);

CREATE TABLE OrderItem (
  Order_ID INTEGER REFERENCES Orders(ID),
  Item_ID INTEGER REFERENCES Item(ID)
);